=== cloudest-y/IBM-Experiments/hw.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT studentlist (student)+>
<!ELEMENT student (name,age,id)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ATTLIST student major (Marketing|Finance|Accounting|Tourism) #REQUIRED>

=== cloudest-y/IBM-Experiments/hw.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentlist SYSTEM "hw.dtd">
<studentlist>
	<student major= "Marketing">
		<name>Lee</name>
		<age>20</age>
		<id>102</id>
	</student>
	<student major= "Finance">
		<name>Tom</name>
		<age>21</age>
		<id>105</id>
	</student>
	<student major= "Accounting">
		<name>Susan</name>
		<age>19</age>
		<id>107</id>
	</student>
	<student major= "Tourism">
		<name>Peter</name>
		<age>22</age>
		<id>321</id>
	</student>
</studentlist>
